services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: llmzoomcamp_cvs_pvgector
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_DB=faq
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgvector_data: