run:
	uv run python assistant.py

chat:
	uv run streamlit run app.py

dashboard:
	uv run streamlit run dashboard.py

up:
	docker compose up -d

psql:
	docker compose exec postgres psql postgresql://user:password@localhost:5432/course_assistant